apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-app
  namespace: project-dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app

    spec:
      containers:
        - name: my-app

          image: us-central1-docker.pkg.dev/project-1-501612/demo/frontend:IMAGE_TAG

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: BACKEND_URL
              value: "http://my-backend-service"

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"